language: node_js
node_js:
  - '10.14.2'
os:
  - linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- -- version 0.23.2
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn build
after_script:
  - cd ./public
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Update blogs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
  - expect -c "scp -P ${SV_PORT} ./* ${SV_U_NAME}@${SV_HOST}:/data/zidoshare.github.io/ \n expect \"*assword\"\nsend \"${SV_U_PASSWORD}\r\" \n expect eof"
branches:
  only:
    - dev
